---
title: "Lecture 6: Numerical Stability and R Errors"
author: "STAT 385 - James Balamuta"
date: "June 23, 2016"
layout: post
categories: lectures
tags: 
- r
- variance
- arithmetic overflow
- floating precision
- errors
- na
---

# Overview

When writing algorithms to compute different routines, it is imperative that the value the routine produces is correct. To obtain numerically valid results, we need to ensure that the underlying routines are able to work with how the computer is able to represent a data type. In addition, we'll take a quick glance at some common R errors.

# Files of Interest 

Rendered Files:

* [Lecture 6: Numerical Stability and R Errors (PDF)](/assets/lectures/lec6/lec6_numerical_stability_errors_and_debugging_techniques.pdf)

Generation Files:

* [Lecture 6: Numerical Stability and R Errors (Rmd)](/assets/lectures/lec6/lec6_numerical_stability_errors_and_debugging_techniques.Rmd)
* [Lecture 6: Numerical Stability and R Errors (R)](/assets/lectures/lec6/lec6_numerical_stability_errors_and_debugging_techniques.R)


# Source Material

Source of all materials: 

* <http://github.com/coatless/stat385/tree/gh-pages/assets/lectures/lec6>
