---
title: "Lecture 5: Functions, Recursion, Benchmarking, and Memoization"
author: "JJB"
date: "June 21, 2016"
layout: post
categories: lectures
tags: 
- r
- conditional statements
- loops
- functions
- memoization
- benchmarking
---

# Overview

Today, we're going to explore the wonderful world of functions in *R*! As a result, we'll also look at recursive properties that we can exploit and ways to speed up recursive calls. One way is by employing memoization, or caching results, within a function. 

# Files of Interest 

Rendered Files:

* [Lecture 5: Functions, Recursion, Benchmarking, and Memoization (PDF)](/assets/lectures/lec5/lec5_functions_recursion_memoization_benchmarking.pdf)

Generation Files:

* [Lecture 5: Functions, Recursion, Benchmarking, and Memoization (Rmd)](/assets/lectures/lec5/lec5_functions_recursion_memoization_benchmarking.Rmd)
* [Lecture 5: Functions, Recursion, Benchmarking, and Memoization (R)](/assets/lectures/lec5/lec5_functions_recursion_memoization_benchmarking.R)

# Source Material

Source of all materials: 

* <http://github.com/coatless/stat385/tree/gh-pages/assets/lectures/lec5>
