---
title: "Lecture 3: Data Types, Data Structures, and Subsetting"
author: "JJB"
date: "June 16, 2016"
layout: post
categories: lectures
tags: 
- atomic vector
- data types
- missingness
- data structures
- variables
---

# Overview

The object of this lecture is to understand the basic building blocks of *R*: `atomic vectors` and `variables`. To do so, we'll look at the different data types available and describe *R*'s data structures. Special attention will be paid to some interesting properties that *R* possesses regarding recycling.

# Files of Interest 

Rendered Files:

* [Lecture 3: Data Types, Data Structures, and Subsetting (PDF)](/assets/lectures/lec3/lec3_datatypes_data_structures_and_subsetting.pdf)

Generation Files:

* [Lecture 3: Data Types, Data Structures, and Subsetting (Rnw)](/assets/lectures/lec3/lec3_datatypes_data_structures_and_subsetting.R.Rmd)
* [Lecture 3: Data Types, Data Structures, and Subsetting (R)](/assets/lectures/lec3/r_lec3_datatypes_data_structures_and_subsetting.R)

# Source Material

Source of all materials: 

* <http://github.com/coatless/stat385/tree/gh-pages/assets/lectures/lec3>

