---
title: "Lecture 4: Grouping, Control Structures, and Big O"
author: "JJB"
date: "June 20, 2016"
layout: post
categories: lectures
tags: 
- r
- conditional statements
- loops
- big o
- grouping
---

# Overview

As we begin to understand more of the code structures, we will want to understand how to reduce the amount of code used by saving ourselves from copying and pasting code. Thorough this process, we need to consider the underlying time constraints given by different structures. Lastly, we discussed appropriate group etiquette and different techniques to use. 

# Files of Interest 

Rendered Files:

* [Lecture 4: Grouping, Control Structures, and Big O (PDF)](/assets/lectures/lec4/lec4_grouping_big_oh_control_statements.pdf)

Generation Files:

* [Lecture 4: Grouping, Control Structures, and Big O (Rmd)](/assets/lectures/lec4/lec4_grouping_big_oh_control_statements.Rmd)
* [Lecture 4: Grouping, Control Structures, and Big O (R)](/assets/lectures/lec4/lec4_grouping_big_oh_control_statements.R)

# Source Material

Source of all materials: 

* <http://github.com/coatless/stat385/tree/gh-pages/assets/lectures/lec4>

