---
title: "Lecture 8: Data Management Techniques, Regular Expressions, Date and Time"
author: "STAT 385 - James Balamuta"
date: "June 27, 2016"
layout: post
categories: lectures
tags: 
- r
- data.frame
- regex
- regular expressions
- date
- time
- manipulation
---

# Overview

Part of working within R is being able to understand data. Within this lecture,
we talk about a few different ideal data management techniques. In addition,
we discuss the powerful use of regex as well as date time stamps.

# Files of Interest 

Rendered Files:

* [Lecture 8: Data Management Techniques, Regular Expressions, Date and Time (PDF)](/assets/lectures/lec8/lec8_data_management_techniques_regular_expressions_dates_and_times.pdf)

Generation Files:

* [Lecture 8: Data Management Techniques, Regular Expressions, Date and Time (Rmd)](/assets/lectures/lec8/lec8_data_management_techniques_regular_expressions_dates_and_times.Rmd)
* [Lecture 8: Data Management Techniques, Regular Expressions, Date and Time (R)](/assets/lectures/lec8/lec8_data_management_techniques_regular_expressions_dates_and_times.R)


# Source Material

Source of all materials: 

* <http://github.com/coatless/stat385/tree/gh-pages/assets/lectures/lec8>
